server:
    port: 8080

spring:
    profiles:
      active: heroku
    queries:
      users-query: select username, password from users where username=?
      roles-query: select u.username, r.role from users u inner join user_role ur on(u.id=ur.user_id) inner join role r on(ur.role_id=r.id) where u.username=?
---
spring:
    profiles: dev
    main:
        web-environment: false
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
        dialect: org.hibernate.dialect.PostgreSQLDialect
        max-active: 5
        max-pool: 10
        max-idle: 0
    jpa:
        properties:
                    hibernate:
                        temp:
                            use_jdbc_metadata_defaults: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    queries:
        users-query: select username, password from users where username=?
        roles-query: select u.username, r.role from users u inner join user_role ur on(u.id=ur.user_id) inner join role r on(ur.role_id=r.id) where u.username=?
---
server:
    port: 8090

spring:
    profile: heroku
    main:
        web-environment: false
    datasource:
        url: jdbc:postgresql://ec2-54-163-228-58.compute-1.amazonaws.com:5432/dfvo2f9it4pmk9?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
        username: ucokaucbriaged
        password:
        driver-class-name: org.postgresql.Driver
        dialect: org.hibernate.dialect.PostgreSQLDialect
        max-active: 5
        max-pool: 10
        max-idle: 0
    jpa:
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect